services:
  # Web Service
  - type: web
    name: andela-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_BASE_URL
        value: https://openrouter.ai/api/v1
      - key: MODEL_NAME
        value: openai/gpt-4o-mini
      - key: MCP_SERVER_URL
        value: https://vipfapwm3x.us-east-1.awsapprunner.com/mcp
      - key: TEMPERATURE
        value: 0.7
      - key: MAX_TOKENS
        value: 700
      - key: PYTHON_VERSION
        value: 3.11.0
